### ISSUE TITLE
Discord helper bot not responding to the commands in user messages

### ISSUE THREAD

**Issue by mohanch16** [mohanch16/discord-help-bot#1]
Please follow the link in repo readme file, generate your own API keys for the bot and connect to a discord channel for testing the functionality of the app.

Issue: when user sent message contains a command to be addressed, bot is not responding but showing as online.

**Comment by ArjunSharda** [comment]
Was the bot working previously before a new update?

**Comment by mohanch16** [comment]
No, It was just showing as online but not responding. There's been a long gap since I worked on this.  

From what I remember, event handler was being triggered but the message content was not matching the help command. I know, it feels weird that the code is doing string comparison rather than substring matching. But my rust skills are little rusty now. I will definitely give it a go this weekend and see if the edition year is the culprit, like you mentioned in the PR. But I remember that console logs were fine (i.e., my app was able to connect the discord channel and trigger the event handler and log messages to console as in the code).

**Comment by ArjunSharda** [comment]
I know this has happened to me in Python and JavaScript. It's technically a error when the bot starts up like message related, etc.
